export const PRODUCT_REQUEST = "PRODUCT_REQUEST";

export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

//POST

export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";

//GET
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
